import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Hero from "../components/Home/Hero/Hero";
import PopularDishes from "../components/Home/PopularDishes/PopularDishes";
import WeAreMultipleService from "../components/Home/MultipleService/WeAreMultipleService";
import MenuPack from "../components/Home/MenuPack/MenuPack";
import ReServeTable from "../components/Home/ReServeTable/ReServeTable";
import Demo from "../components/Demo";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Olympia Resturent - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <PopularDishes />
      <WeAreMultipleService />
      <MenuPack />
      <ReServeTable />
      {/* <Demo /> */}
    </>
  );
}
